/* Answer checking for the self-study ladders. Generated by
   tools/tex2html.py -- edit that, not this file.

   Deliberately forgiving: a student who has the chemistry right should not
   lose the exchange to formatting. Units are optional, commas and spaces in
   numbers are ignored, and scientific notation is accepted in three
   spellings. Significant figures never make an answer wrong -- they earn a
   nudge, because this is practice material, not the exam. */
(function () {
  "use strict";
  var TOL = 0.01;                       // 1% relative tolerance

  function sigfigs(s) {
    s = String(s).trim().replace(/^[+-]/, "");
    if (/e/i.test(s)) s = s.split(/e/i)[0];
    if (s.indexOf(".") >= 0) {
      return s.replace(".", "").replace(/^0+/, "").length || 1;
    }
    return s.replace(/^0+/, "").replace(/0+$/, "").length || 1;
  }

  /* First number in free text: "1900", "1,900 torr", "1.9e3", "1.2 x 10^24" */
  function parseEntry(raw) {
    var t = String(raw).trim().replace(/,/g, "");
    var m = t.match(/^([+-]?\d*\.?\d+(?:[eE][+-]?\d+)?)\s*(?:x|X|\*|\u00d7)\s*10\s*\^?\s*\{?([+-]?\d+)\}?\s*(.*)$/);
    if (m) {
      return { value: parseFloat(m[1]) * Math.pow(10, parseInt(m[2], 10)),
               sig: sigfigs(m[1]), unit: m[3].trim() };
    }
    m = t.match(/^([+-]?\d*\.?\d+(?:[eE][+-]?\d+)?)\s*(.*)$/);
    if (m) {
      return { value: parseFloat(m[1]), sig: sigfigs(m[1]), unit: m[2].trim() };
    }
    return null;
  }

  function normUnit(u) {
    return String(u).toLowerCase().replace(/[.\s]/g, "")
             .replace(/^degrees?/, "deg").replace(/celcius$/, "celsius");
  }

  function feedback(el, cls, msg) {
    el.className = "ansfeedback " + cls;
    el.textContent = msg;
  }

  function check(input) {
    var fb = input.parentNode.querySelector(".ansfeedback");
    var raw = input.value.trim();
    input.classList.remove("ok", "no", "warn");
    if (!raw) { feedback(fb, "", ""); return; }

    var got = parseEntry(raw);
    if (!got) { feedback(fb, "hint", "enter a number"); return; }

    var exp = parseFloat(input.getAttribute("data-val"));
    var expSig = parseInt(input.getAttribute("data-sig"), 10);
    var expUnit = (input.getAttribute("data-unit") || "").trim();
    var rel = Math.abs(got.value - exp) / Math.max(Math.abs(exp), 1e-12);

    if (rel > TOL) {
      input.classList.add("no");
      feedback(fb, "no", "not right \u2014 try again");
      return;
    }
    /* Right number, wrong unit is not "correct" -- but calling it wrong
       would punish a student who typed "atmospheres" for "atm". Third
       state: neither green nor red, and name the unit we wanted. */
    if (expUnit && got.unit && normUnit(got.unit) !== normUnit(expUnit)) {
      input.classList.add("warn");
      feedback(fb, "hint",
               "right number \u2014 check your units (expected " + expUnit + ")");
      return;
    }
    input.classList.add("ok");
    /* Sig figs nudge only when the value was ROUNDED differently. An exact
       match written to more places (1.90e3 for 1900) is not an error. */
    if (rel > 1e-9 && got.sig !== expSig) {
      feedback(fb, "hint", "correct \u2014 check your significant figures");
    } else {
      feedback(fb, "ok", "correct");
    }
  }

  function showAnswer(row) {
    var rev = row.querySelector(".ansreveal");
    if (rev) { rev.removeAttribute("hidden"); }
  }

  document.addEventListener("click", function (e) {
    var t = e.target;
    if (!t.classList) { return; }
    if (t.classList.contains("anscheck")) {
      check(t.parentNode.querySelector(".ansinput"));
    } else if (t.classList.contains("ansshow")) {
      showAnswer(t.parentNode);
    } else if (t.classList.contains("reveal-btn")) {
      var body = t.nextElementSibling;
      var opening = body.hasAttribute("hidden");
      if (opening) { body.removeAttribute("hidden"); }
      else { body.setAttribute("hidden", ""); }
      t.setAttribute("aria-expanded", opening ? "true" : "false");
      t.textContent = opening ? t.getAttribute("data-hide")
                              : t.getAttribute("data-show");
    }
  });

  document.addEventListener("keydown", function (e) {
    if (e.key !== "Enter" || !e.target.classList) { return; }
    if (!e.target.classList.contains("ansinput")) { return; }
    e.preventDefault();
    if (e.target.getAttribute("data-check") === "num") { check(e.target); }
    else { showAnswer(e.target.parentNode); }
  });

  /* ---- scratch pads: persistence, and an optional equation editor ----

     Saved per browser under a stable pad id, so a refresh mid-ladder does
     not lose a student's working. Never leaves their device.

     Pads flagged data-math upgrade to a MathLive <math-field> the first
     time they are focused. The library is ~1 MB, so it is fetched only on
     that first focus: a student who works on paper and just types answers
     downloads none of it. */

  var PAD_KEY = "apchem:scratch:";
  var MATHLIVE_URL =
    "https://cdn.jsdelivr.net/npm/mathlive@0.104.2/dist/mathlive.min.mjs";
  var mathlivePromise = null;

  function padKey(el) { return PAD_KEY + el.getAttribute("data-pad"); }

  function save(el) {
    var k = el.getAttribute("data-pad");
    if (!k) { return; }
    try {
      if (el.value) { localStorage.setItem(padKey(el), el.value); }
      else { localStorage.removeItem(padKey(el)); }
    } catch (e) { /* private mode, quota, storage disabled -- ignore */ }
  }

  function restore(el) {
    try {
      var v = localStorage.getItem(padKey(el));
      if (v) { el.value = v; }
    } catch (e) { /* ignore */ }
  }

  function loadMathLive() {
    if (!mathlivePromise) {
      mathlivePromise = import(MATHLIVE_URL).then(function (m) {
        /* Sounds are another ~227 KB and a keyclick in a quiet room is not
           what anyone wants. */
        if (m.MathfieldElement) { m.MathfieldElement.soundsDirectory = null; }
        return m;
      });
    }
    return mathlivePromise;
  }

  function upgrade(ta) {
    ta.setAttribute("data-upgrading", "1");
    loadMathLive().then(function () {
      var mf = document.createElement("math-field");
      mf.className = "scratch mathfield";
      mf.setAttribute("data-pad", ta.getAttribute("data-pad"));
      mf.setAttribute("aria-label", "working space");
      if (ta.style.height) { mf.style.minHeight = ta.style.height; }
      mf.value = ta.value || "";
      mf.addEventListener("input", function () { save(mf); });
      ta.parentNode.replaceChild(mf, ta);
      mf.focus();
    }).catch(function () {
      /* Offline, or a filter blocking the CDN. The textarea still works --
         leave it alone rather than break the pad. */
      ta.removeAttribute("data-math");
      ta.removeAttribute("data-upgrading");
    });
  }

  function initPads() {
    var pads = document.querySelectorAll("textarea.scratch[data-pad]");
    for (var i = 0; i < pads.length; i++) { restore(pads[i]); }
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initPads);
  } else {
    initPads();
  }

  document.addEventListener("input", function (e) {
    if (e.target.classList && e.target.classList.contains("scratch")) {
      save(e.target);
    }
  });

  document.addEventListener("focusin", function (e) {
    var t = e.target;
    if (!t.classList || !t.classList.contains("scratch")) { return; }
    if (t.tagName !== "TEXTAREA") { return; }
    if (!t.getAttribute("data-math") || t.getAttribute("data-upgrading")) {
      return;
    }
    upgrade(t);
  });

})();
