/* Answer checking for the self-study ladders. Generated by
   tools/tex2html.py -- edit that, not this file.

   Deliberately forgiving: a student who has the chemistry right should not
   lose the exchange to formatting. Units are optional, commas and spaces in
   numbers are ignored, and scientific notation is accepted in three
   spellings. Significant figures never make an answer wrong -- they earn a
   nudge, because this is practice material, not the exam. */
(function () {
  "use strict";
  var TOL = 0.01;                       // 1% relative tolerance

  function sigfigs(s) {
    s = String(s).trim().replace(/^[+-]/, "");
    if (/e/i.test(s)) s = s.split(/e/i)[0];
    if (s.indexOf(".") >= 0) {
      return s.replace(".", "").replace(/^0+/, "").length || 1;
    }
    return s.replace(/^0+/, "").replace(/0+$/, "").length || 1;
  }

  /* First number in free text: "1900", "1,900 torr", "1.9e3", "1.2 x 10^24" */
  function parseEntry(raw) {
    var t = String(raw).trim().replace(/,/g, "");
    var m = t.match(/^([+-]?\d*\.?\d+(?:[eE][+-]?\d+)?)\s*(?:x|X|\*|\u00d7)\s*10\s*\^?\s*\{?([+-]?\d+)\}?\s*(.*)$/);
    if (m) {
      return { value: parseFloat(m[1]) * Math.pow(10, parseInt(m[2], 10)),
               sig: sigfigs(m[1]), unit: m[3].trim() };
    }
    m = t.match(/^([+-]?\d*\.?\d+(?:[eE][+-]?\d+)?)\s*(.*)$/);
    if (m) {
      return { value: parseFloat(m[1]), sig: sigfigs(m[1]), unit: m[2].trim() };
    }
    return null;
  }

  function normUnit(u) {
    return String(u).toLowerCase().replace(/[.\s]/g, "")
             .replace(/^degrees?/, "deg").replace(/celcius$/, "celsius");
  }

  function feedback(el, cls, msg) {
    el.className = "ansfeedback " + cls;
    el.textContent = msg;
  }

  function check(input) {
    var fb = input.parentNode.querySelector(".ansfeedback");
    var raw = input.value.trim();
    input.classList.remove("ok", "no", "warn");
    if (!raw) { feedback(fb, "", ""); return; }

    var got = parseEntry(raw);
    if (!got) { feedback(fb, "hint", "enter a number"); return; }

    var exp = parseFloat(input.getAttribute("data-val"));
    var expSig = parseInt(input.getAttribute("data-sig"), 10);
    var expUnit = (input.getAttribute("data-unit") || "").trim();
    var rel = Math.abs(got.value - exp) / Math.max(Math.abs(exp), 1e-12);

    if (rel > TOL) {
      input.classList.add("no");
      feedback(fb, "no", "not right \u2014 try again");
      return;
    }
    /* Right number, wrong unit is not "correct" -- but calling it wrong
       would punish a student who typed "atmospheres" for "atm". Third
       state: neither green nor red, and name the unit we wanted. */
    if (expUnit && got.unit && normUnit(got.unit) !== normUnit(expUnit)) {
      input.classList.add("warn");
      feedback(fb, "hint",
               "right number \u2014 check your units (expected " + expUnit + ")");
      return;
    }
    input.classList.add("ok");
    /* Sig figs nudge only when the value was ROUNDED differently. An exact
       match written to more places (1.90e3 for 1900) is not an error. */
    if (rel > 1e-9 && got.sig !== expSig) {
      feedback(fb, "hint", "correct \u2014 check your significant figures");
    } else {
      feedback(fb, "ok", "correct");
    }
  }

  function showAnswer(row) {
    var rev = row.querySelector(".ansreveal");
    if (rev) { rev.removeAttribute("hidden"); }
  }

  document.addEventListener("click", function (e) {
    var t = e.target;
    if (!t.classList) { return; }
    if (t.classList.contains("anscheck")) {
      check(t.parentNode.querySelector(".ansinput"));
    } else if (t.classList.contains("ansshow")) {
      showAnswer(t.parentNode);
    } else if (t.classList.contains("reveal-btn")) {
      var body = t.nextElementSibling;
      var opening = body.hasAttribute("hidden");
      if (opening) { body.removeAttribute("hidden"); }
      else { body.setAttribute("hidden", ""); }
      t.setAttribute("aria-expanded", opening ? "true" : "false");
      t.textContent = opening ? t.getAttribute("data-hide")
                              : t.getAttribute("data-show");
    }
  });

  document.addEventListener("keydown", function (e) {
    if (e.key !== "Enter" || !e.target.classList) { return; }
    if (!e.target.classList.contains("ansinput")) { return; }
    e.preventDefault();
    if (e.target.getAttribute("data-check") === "num") { check(e.target); }
    else { showAnswer(e.target.parentNode); }
  });
})();
